title: CSE599H
description: Advances and Challenges in Language Models, Reasoning, and AI Agents
theme: just-the-docs

# url: https://courses.cs.washington.edu/courses/cse599h/25sp/

aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template
  Gradescope: https://www.gradescope.com/courses/1007475
  Ed: https://edstem.org/us/courses/50883